// Handwritten regression fixtures, not evidence of live model design quality.
export function projectFixture(brand = 'mochi') {
  const soft = brand === 'mochi';
  const title = soft ? 'Mad Mochi' : 'Forma Studio';
  const font = soft ? 'Brand Sans' : 'Brand Serif';
  const files = {
    'package.json': JSON.stringify({ dependencies: { react: '18.2.0', 'react-dom': '18.2.0' } }),
    'index.html': `<!doctype html><html lang="pl"><head><title>${title}</title><meta name="description" content="Projekt testowy"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Head+Font:wght@400;700&display=swap"></head><body><div id="root"></div></body></html>`,
    'src/main.tsx': `import React from 'react';import {createRoot} from 'react-dom/client';import App from './App';import './index.css';createRoot(document.getElementById('root')!).render(<App/>);`,
    'src/App.tsx': `import Nav from './components/Nav';import Hero from './sections/Hero';export default function App(){return <><Nav/><main><Hero/><section id="more"><h2>${soft ? 'Mała przerwa, dużo przyjemności.' : 'Przestrzeń ma znaczenie.'}</h2><p>Układ kontrolny do testowania typografii, stylów i responsywności.</p></section></main><footer>${title} · Projekt testowy</footer></>}`,
    'src/components/Nav.tsx': `export default function Nav(){return <nav><a className="brand" href="#top">${title}</a><div><a href="#more">${soft ? 'Nasza historia' : 'Podejście'}</a><a className="contact" href="mailto:hello@brand.test">Kontakt</a></div></nav>}`,
    'src/sections/Hero.tsx': `import styles from './Hero.module.css';import icon from '../mark.svg';export default function Hero(){return <section id="top" className="hero"><div><p className="eyebrow">${soft ? 'MOCHI · MATCHA · MAŁE PRZYJEMNOŚCI' : 'ARCHITEKTURA / WNĘTRZA'}</p><h1>${soft ? 'Miękko.\nSłodko.\nPo swojemu.' : 'Mniej formy.\nWięcej\nprzestrzeni.'}</h1><p className="intro">${soft ? 'Chwila dla Ciebie, w odcieniach matchy i sakury.' : 'Spokojna kompozycja. Światło. Proporcje.'}</p><a className="cta" href="#more">Poznaj nas <img alt="" src={icon}/></a></div><div className={styles.art} aria-label="Dekoracyjna ilustracja"><div className="shape a"/><div className="shape b"/><span>${soft ? 'soft / slow / sweet' : 'FORM / SPACE / LIGHT'}</span></div></section>}`,
    'src/sections/Hero.module.css': `.art{position:relative;isolation:isolate;overflow:hidden;min-height:440px;background:${soft ? '#ebadc0' : '#d4d0c6'};border-radius:${soft ? '45% 45% 12px 12px' : '0'};display:grid;place-items:end center;padding:36px;font-size:14px;letter-spacing:.12em}`,
    'src/mark.svg': '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3 12h16m-6-6 6 6-6 6" fill="none" stroke="currentColor" stroke-width="2"/></svg>',
    'src/index.css': `@import url('https://fonts.googleapis.com/css2?family=${font.replace(' ', '+')}:wght@400;700&display=swap');\n@import './layout.css';\n:root{--bg:${soft ? '#fff8f0' : '#f0efe9'};--ink:${soft ? '#342b27' : '#262c28'};--accent:${soft ? '#597849' : '#262c28'};}body{background:var(--bg);color:var(--ink);font-family:'${font}',${soft ? 'sans-serif' : 'serif'};line-height:1.6}h1{font-family:'Head Font',serif;font-size:clamp(48px,6vw,88px);line-height:1.04;letter-spacing:-.055em;white-space:pre-line;font-weight:400;margin:20px 0}h2{font-size:clamp(28px,4vw,50px);line-height:1.15;font-weight:400}a{color:inherit;text-decoration:none}a:focus-visible{outline:3px solid var(--accent);outline-offset:4px}.brand{font-size:24px;font-weight:700}.eyebrow{font-size:12px;letter-spacing:.15em}.intro{font-size:18px;max-width:34ch}.cta{display:inline-flex;align-items:center;gap:12px;background:var(--accent);color:white;padding:14px 24px;border-radius:${soft ? '20px' : '0'};margin-top:18px}.cta img{width:20px;height:20px}.shape{position:absolute;z-index:-1;background:${soft ? '#fff8f0' : '#92958b'};width:220px;height:220px;border-radius:${soft ? '50%' : '0'};top:80px;left:50px;transform:rotate(-15deg)}.shape.b{background:${soft ? '#597849' : '#eff0e9'};top:140px;left:140px}.cta{transition:transform .2s}.cta:hover{transform:translateY(-2px)}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}`,
    'src/layout.css': `nav{display:flex;align-items:center;justify-content:space-between;padding:24px max(24px,calc((100vw - 1120px)/2));gap:20px;border-bottom:1px solid #0002}nav div{display:flex;gap:24px;align-items:center}.hero{max-width:1120px;margin:auto;display:grid;grid-template-columns:1.1fr 1fr;gap:64px;align-items:center;padding:64px 24px}#more{max-width:1120px;margin:auto;padding:64px 24px 96px;border-top:1px solid #0002}footer{padding:24px;text-align:center;border-top:1px solid #0002;font-size:13px}nav a{white-space:nowrap}@media(max-width:720px){nav{padding:20px}nav div{gap:16px}.contact{display:none}.hero{grid-template-columns:1fr;gap:32px;padding-top:36px}#more{padding-top:48px}}`,
    'src/unused.css': 'body{display:none!important}',
  };
  return Object.fromEntries(Object.entries(files).map(([k, v]) => ['main/frontend/' + k, v]));
}
